-- =====================================================================
-- KRISHIMITRA — STORED PROCEDURES
-- Run after schema.sql, seed.sql and functions.sql
-- =====================================================================

BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE ADD_FARM'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE GENERATE_RECOMMENDATIONS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE RECORD_HARVEST'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ---------------------------------------------------------------------
-- ADD_FARM
-- Encapsulates farm creation as a single transactional unit: validates
-- the farmer exists and is active, inserts the farm, and commits only
-- if everything succeeds (rolls back on any error).
-- ---------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE ADD_FARM (
    p_farmer_id     IN  FARMER.FARMER_ID%TYPE,
    p_farm_name     IN  FARM.FARM_NAME%TYPE,
    p_location      IN  FARM.LOCATION%TYPE,
    p_land_area     IN  FARM.LAND_AREA_ACRES%TYPE,
    p_soil_id       IN  FARM.SOIL_ID%TYPE,
    p_irrigation    IN  FARM.IRRIGATION_TYPE%TYPE,
    p_water_avail   IN  FARM.WATER_AVAILABILITY%TYPE,
    p_season_id     IN  FARM.CURRENT_SEASON_ID%TYPE,
    p_notes         IN  FARM.NOTES%TYPE,
    p_farm_id       OUT FARM.FARM_ID%TYPE
)
IS
    v_status FARMER.STATUS%TYPE;
BEGIN
    SELECT STATUS INTO v_status FROM FARMER WHERE FARMER_ID = p_farmer_id FOR UPDATE;

    IF v_status != 'ACTIVE' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Farmer account is not active.');
    END IF;

    p_farm_id := SEQ_FARM_ID.NEXTVAL;

    INSERT INTO FARM (FARM_ID, FARMER_ID, FARM_NAME, LOCATION, LAND_AREA_ACRES,
                       SOIL_ID, IRRIGATION_TYPE, WATER_AVAILABILITY, CURRENT_SEASON_ID, NOTES)
    VALUES (p_farm_id, p_farmer_id, p_farm_name, p_location, p_land_area,
            p_soil_id, p_irrigation, p_water_avail, p_season_id, p_notes);

    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Farmer not found.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END ADD_FARM;
/

-- ---------------------------------------------------------------------
-- GENERATE_RECOMMENDATIONS
-- Runs CALCULATE_CROP_SCORE for every active crop against one farm,
-- persists the top-N results into RECOMMENDATION (tagged with the
-- given scenario tag so "CURRENT" vs "WHAT_IF" runs can both be
-- stored), and returns them as a REF CURSOR to the caller.
-- Demonstrates a multi-step transaction: DELETE old rows for this
-- scenario, INSERT the fresh set, COMMIT together.
-- ---------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GENERATE_RECOMMENDATIONS (
    p_farm_id       IN  FARM.FARM_ID%TYPE,
    p_soil_id       IN  SOIL.SOIL_ID%TYPE,
    p_season_id     IN  SEASON.SEASON_ID%TYPE,
    p_water_avail   IN  VARCHAR2,
    p_budget        IN  NUMBER,
    p_land_area     IN  NUMBER,
    p_last_crop_id  IN  CROP.CROP_ID%TYPE DEFAULT NULL,
    p_scenario_tag  IN  VARCHAR2 DEFAULT 'CURRENT',
    p_top_n         IN  NUMBER DEFAULT 5,
    p_results       OUT SYS_REFCURSOR
)
IS
BEGIN
    DELETE FROM RECOMMENDATION
     WHERE FARM_ID = p_farm_id AND SCENARIO_TAG = p_scenario_tag;

    INSERT INTO RECOMMENDATION (RECOMMENDATION_ID, FARM_ID, CROP_ID, SUITABILITY_SCORE, RISK_LABEL, EXPLANATION, SCENARIO_TAG)
    SELECT SEQ_RECOMMENDATION_ID.NEXTVAL,
           p_farm_id,
           c.CROP_ID,
           CALCULATE_CROP_SCORE(c.CROP_ID, p_soil_id, p_season_id, p_water_avail, p_budget, p_land_area, p_last_crop_id),
           CASE
               WHEN CALCULATE_RISK_SCORE(c.CROP_ID, p_water_avail) < 35 THEN 'LOW RISK'
               WHEN CALCULATE_RISK_SCORE(c.CROP_ID, p_water_avail) < 60 THEN 'MEDIUM RISK'
               ELSE 'HIGH RISK'
           END,
           'Auto-generated by GENERATE_RECOMMENDATIONS on ' || TO_CHAR(SYSDATE, 'DD-MON-YYYY HH24:MI'),
           p_scenario_tag
      FROM CROP c
     WHERE c.IS_ACTIVE = 1;

    COMMIT;

    OPEN p_results FOR
        SELECT r.RECOMMENDATION_ID, r.CROP_ID, c.CROP_NAME, r.SUITABILITY_SCORE, r.RISK_LABEL
          FROM RECOMMENDATION r
          JOIN CROP c ON c.CROP_ID = r.CROP_ID
         WHERE r.FARM_ID = p_farm_id AND r.SCENARIO_TAG = p_scenario_tag
         ORDER BY r.SUITABILITY_SCORE DESC
         FETCH FIRST p_top_n ROWS ONLY;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END GENERATE_RECOMMENDATIONS;
/

-- ---------------------------------------------------------------------
-- RECORD_HARVEST
-- Closes out a CROP_HISTORY entry: sets harvest date/yield/cost/revenue
-- and computes profit via CALCULATE_PROFIT, as a single transaction.
-- The AFTER UPDATE trigger TRG_CROP_HISTORY_PROFIT independently
-- guards profit consistency at the table level as a safety net.
-- ---------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE RECORD_HARVEST (
    p_history_id     IN CROP_HISTORY.HISTORY_ID%TYPE,
    p_harvest_date   IN CROP_HISTORY.HARVEST_DATE%TYPE,
    p_yield_qtl      IN CROP_HISTORY.YIELD_QTL%TYPE,
    p_total_cost     IN CROP_HISTORY.TOTAL_COST%TYPE,
    p_revenue        IN CROP_HISTORY.REVENUE%TYPE
)
IS
BEGIN
    UPDATE CROP_HISTORY
       SET HARVEST_DATE = p_harvest_date,
           YIELD_QTL    = p_yield_qtl,
           TOTAL_COST   = p_total_cost,
           REVENUE      = p_revenue,
           PROFIT       = CALCULATE_PROFIT(p_revenue, p_total_cost)
     WHERE HISTORY_ID = p_history_id;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Crop history record not found.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END RECORD_HARVEST;
/
