-- =====================================================================
-- KRISHIMITRA — ORACLE DATABASE SCHEMA
-- Farmer & Crop Decision Support Platform
-- =====================================================================
-- Run this script as the KRISHIMITRA schema owner (or a user with
-- CREATE TABLE / SEQUENCE / VIEW / PROCEDURE / TRIGGER privileges).
--
-- Order of execution for the full database build:
--   1. schema.sql      (this file)
--   2. seed.sql
--   3. views.sql
--   4. functions.sql
--   5. procedures.sql
--   6. triggers.sql
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. CLEAN SLATE (drop in reverse dependency order, ignore "not exists")
-- ---------------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RECOMMENDATION CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CROP_HISTORY CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CROP_RISK CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CROP_RESOURCE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CROP_COST CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CROP_SEASON CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CROP_SOIL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RESOURCE_ITEM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CROP CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SEASON CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SOIL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FARM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FARMER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ADMIN_USER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FARMER_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FARM_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SOIL_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SEASON_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CROP_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESOURCE_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CROP_COST_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CROP_RISK_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CROP_HISTORY_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RECOMMENDATION_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ADMIN_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ---------------------------------------------------------------------
-- 1. SEQUENCES
-- ---------------------------------------------------------------------
CREATE SEQUENCE SEQ_FARMER_ID          START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FARM_ID            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SOIL_ID            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SEASON_ID          START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CROP_ID            START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESOURCE_ID        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CROP_COST_ID       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CROP_RISK_ID       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CROP_HISTORY_ID    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RECOMMENDATION_ID  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ADMIN_ID           START WITH 1 INCREMENT BY 1 NOCACHE;

-- ---------------------------------------------------------------------
-- 2. LOOKUP TABLES: SOIL, SEASON, RESOURCE_ITEM
--    (kept separate from CROP so soil/season/resource facts are stored
--     once and referenced, not duplicated per crop -> 3NF)
-- ---------------------------------------------------------------------
CREATE TABLE SOIL (
    SOIL_ID         NUMBER(6)        NOT NULL,
    SOIL_NAME       VARCHAR2(40)     NOT NULL,
    DESCRIPTION     VARCHAR2(300),
    CONSTRAINT PK_SOIL PRIMARY KEY (SOIL_ID),
    CONSTRAINT UQ_SOIL_NAME UNIQUE (SOIL_NAME)
);

CREATE TABLE SEASON (
    SEASON_ID       NUMBER(6)        NOT NULL,
    SEASON_NAME     VARCHAR2(20)     NOT NULL,
    DESCRIPTION     VARCHAR2(300),
    START_MONTH     NUMBER(2)        CHECK (START_MONTH BETWEEN 1 AND 12),
    END_MONTH       NUMBER(2)        CHECK (END_MONTH BETWEEN 1 AND 12),
    CONSTRAINT PK_SEASON PRIMARY KEY (SEASON_ID),
    CONSTRAINT UQ_SEASON_NAME UNIQUE (SEASON_NAME)
);

CREATE TABLE RESOURCE_ITEM (
    RESOURCE_ID     NUMBER(6)        NOT NULL,
    RESOURCE_NAME   VARCHAR2(60)     NOT NULL,
    RESOURCE_TYPE   VARCHAR2(30)     NOT NULL
                       CHECK (RESOURCE_TYPE IN ('SEED','FERTILIZER','PESTICIDE','EQUIPMENT','LABOUR','OTHER')),
    UNIT            VARCHAR2(20),
    AVG_UNIT_COST   NUMBER(10,2)     CHECK (AVG_UNIT_COST >= 0),
    CONSTRAINT PK_RESOURCE PRIMARY KEY (RESOURCE_ID),
    CONSTRAINT UQ_RESOURCE_NAME UNIQUE (RESOURCE_NAME)
);

-- ---------------------------------------------------------------------
-- 3. ADMIN_USER — separate identity space from FARMER (role separation)
-- ---------------------------------------------------------------------
CREATE TABLE ADMIN_USER (
    ADMIN_ID        NUMBER(6)        NOT NULL,
    FULL_NAME       VARCHAR2(100)    NOT NULL,
    EMAIL           VARCHAR2(120)    NOT NULL,
    PASSWORD_HASH   VARCHAR2(255)    NOT NULL,
    CREATED_AT      TIMESTAMP        DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_ADMIN PRIMARY KEY (ADMIN_ID),
    CONSTRAINT UQ_ADMIN_EMAIL UNIQUE (EMAIL)
);

-- ---------------------------------------------------------------------
-- 4. FARMER
-- ---------------------------------------------------------------------
CREATE TABLE FARMER (
    FARMER_ID       NUMBER(10)       NOT NULL,
    FULL_NAME       VARCHAR2(100)    NOT NULL,
    EMAIL           VARCHAR2(120)    NOT NULL,
    PHONE           VARCHAR2(15)     NOT NULL,
    PASSWORD_HASH   VARCHAR2(255)    NOT NULL,
    STATE           VARCHAR2(60),
    DISTRICT        VARCHAR2(60),
    STATUS          VARCHAR2(10)     DEFAULT 'ACTIVE' NOT NULL
                       CHECK (STATUS IN ('ACTIVE','BLOCKED')),
    CREATED_AT      TIMESTAMP        DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP        DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_FARMER PRIMARY KEY (FARMER_ID),
    CONSTRAINT UQ_FARMER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_FARMER_PHONE CHECK (LENGTH(PHONE) BETWEEN 10 AND 15)
);
CREATE INDEX IDX_FARMER_EMAIL ON FARMER (EMAIL);

-- ---------------------------------------------------------------------
-- 5. FARM — one farmer can own many farms (1 : M)
-- ---------------------------------------------------------------------
CREATE TABLE FARM (
    FARM_ID           NUMBER(10)     NOT NULL,
    FARMER_ID         NUMBER(10)     NOT NULL,
    FARM_NAME         VARCHAR2(100)  NOT NULL,
    LOCATION          VARCHAR2(150)  NOT NULL,
    LAND_AREA_ACRES   NUMBER(8,2)    NOT NULL CHECK (LAND_AREA_ACRES > 0),
    SOIL_ID           NUMBER(6)      NOT NULL,
    IRRIGATION_TYPE   VARCHAR2(20)   NOT NULL
                         CHECK (IRRIGATION_TYPE IN ('RAINFED','BOREWELL','CANAL','DRIP','SPRINKLER')),
    WATER_AVAILABILITY VARCHAR2(10)  NOT NULL
                         CHECK (WATER_AVAILABILITY IN ('LOW','MODERATE','HIGH')),
    CURRENT_SEASON_ID NUMBER(6),
    NOTES             VARCHAR2(500),
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_FARM PRIMARY KEY (FARM_ID),
    CONSTRAINT FK_FARM_FARMER FOREIGN KEY (FARMER_ID) REFERENCES FARMER (FARMER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FARM_SOIL   FOREIGN KEY (SOIL_ID)   REFERENCES SOIL (SOIL_ID),
    CONSTRAINT FK_FARM_SEASON FOREIGN KEY (CURRENT_SEASON_ID) REFERENCES SEASON (SEASON_ID)
);
CREATE INDEX IDX_FARM_FARMER ON FARM (FARMER_ID);

-- ---------------------------------------------------------------------
-- 6. CROP — master crop catalogue (facts intrinsic to the crop only;
--    soil/season/resource suitability lives in junction tables so a
--    crop-soil or crop-season fact is stored exactly once each)
-- ---------------------------------------------------------------------
CREATE TABLE CROP (
    CROP_ID             NUMBER(10)    NOT NULL,
    CROP_NAME           VARCHAR2(60)  NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    WATER_REQUIREMENT   VARCHAR2(10)  NOT NULL
                           CHECK (WATER_REQUIREMENT IN ('LOW','MODERATE','HIGH')),
    GROWTH_DURATION_DAYS NUMBER(5)    NOT NULL CHECK (GROWTH_DURATION_DAYS > 0),
    EXPECTED_YIELD_QTL_PER_ACRE NUMBER(8,2) NOT NULL CHECK (EXPECTED_YIELD_QTL_PER_ACRE > 0),
    AVG_SELLING_PRICE_PER_QTL   NUMBER(10,2) NOT NULL CHECK (AVG_SELLING_PRICE_PER_QTL > 0),
    BASE_RISK_LEVEL     VARCHAR2(10)  DEFAULT 'MEDIUM' NOT NULL
                           CHECK (BASE_RISK_LEVEL IN ('LOW','MEDIUM','HIGH')),
    IS_ACTIVE           NUMBER(1)     DEFAULT 1 NOT NULL CHECK (IS_ACTIVE IN (0,1)),
    CREATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP,
    UPDATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_CROP PRIMARY KEY (CROP_ID),
    CONSTRAINT UQ_CROP_NAME UNIQUE (CROP_NAME)
);

-- ---------------------------------------------------------------------
-- 7. CROP_SOIL — M:N junction (a crop can suit many soils, a soil can
--    suit many crops); SUITABILITY_LEVEL avoids a separate free-text
--    "suitable soils" column on CROP.
-- ---------------------------------------------------------------------
CREATE TABLE CROP_SOIL (
    CROP_ID            NUMBER(10)   NOT NULL,
    SOIL_ID            NUMBER(6)    NOT NULL,
    SUITABILITY_LEVEL  VARCHAR2(10) DEFAULT 'GOOD' NOT NULL
                          CHECK (SUITABILITY_LEVEL IN ('EXCELLENT','GOOD','FAIR','POOR')),
    CONSTRAINT PK_CROP_SOIL PRIMARY KEY (CROP_ID, SOIL_ID),
    CONSTRAINT FK_CS_CROP FOREIGN KEY (CROP_ID) REFERENCES CROP (CROP_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CS_SOIL FOREIGN KEY (SOIL_ID) REFERENCES SOIL (SOIL_ID) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- 8. CROP_SEASON — M:N junction
-- ---------------------------------------------------------------------
CREATE TABLE CROP_SEASON (
    CROP_ID     NUMBER(10) NOT NULL,
    SEASON_ID   NUMBER(6)  NOT NULL,
    CONSTRAINT PK_CROP_SEASON PRIMARY KEY (CROP_ID, SEASON_ID),
    CONSTRAINT FK_CSN_CROP   FOREIGN KEY (CROP_ID)   REFERENCES CROP (CROP_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CSN_SEASON FOREIGN KEY (SEASON_ID) REFERENCES SEASON (SEASON_ID) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- 9. CROP_COST — per-acre standard cost breakdown for a crop, used as
--    the default basis for the economics calculator (kept apart from
--    CROP itself since it is a multi-attribute, potentially versioned
--    costing record, not an intrinsic crop attribute)
-- ---------------------------------------------------------------------
CREATE TABLE CROP_COST (
    CROP_COST_ID      NUMBER(10) NOT NULL,
    CROP_ID           NUMBER(10) NOT NULL,
    SEED_COST         NUMBER(10,2) DEFAULT 0 CHECK (SEED_COST >= 0),
    FERTILIZER_COST   NUMBER(10,2) DEFAULT 0 CHECK (FERTILIZER_COST >= 0),
    LABOUR_COST       NUMBER(10,2) DEFAULT 0 CHECK (LABOUR_COST >= 0),
    IRRIGATION_COST   NUMBER(10,2) DEFAULT 0 CHECK (IRRIGATION_COST >= 0),
    OTHER_COST        NUMBER(10,2) DEFAULT 0 CHECK (OTHER_COST >= 0),
    COST_PER_ACRE     NUMBER(10,2) GENERATED ALWAYS AS
                         (SEED_COST + FERTILIZER_COST + LABOUR_COST + IRRIGATION_COST + OTHER_COST) VIRTUAL,
    CONSTRAINT PK_CROP_COST PRIMARY KEY (CROP_COST_ID),
    CONSTRAINT FK_CC_CROP FOREIGN KEY (CROP_ID) REFERENCES CROP (CROP_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_CROP_COST_CROP UNIQUE (CROP_ID)
);

-- ---------------------------------------------------------------------
-- 10. CROP_RESOURCE — M:N junction: which resources a crop typically needs
-- ---------------------------------------------------------------------
CREATE TABLE CROP_RESOURCE (
    CROP_ID       NUMBER(10) NOT NULL,
    RESOURCE_ID   NUMBER(6)  NOT NULL,
    QTY_PER_ACRE  NUMBER(10,2) CHECK (QTY_PER_ACRE >= 0),
    CONSTRAINT PK_CROP_RESOURCE PRIMARY KEY (CROP_ID, RESOURCE_ID),
    CONSTRAINT FK_CR_CROP     FOREIGN KEY (CROP_ID)     REFERENCES CROP (CROP_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CR_RESOURCE FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE_ITEM (RESOURCE_ID) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- 11. CROP_RISK — per-crop, per-risk-type score (normalized instead of
--     five separate risk columns on CROP -> avoids repeating groups, 1NF)
-- ---------------------------------------------------------------------
CREATE TABLE CROP_RISK (
    CROP_RISK_ID  NUMBER(10) NOT NULL,
    CROP_ID       NUMBER(10) NOT NULL,
    RISK_TYPE     VARCHAR2(20) NOT NULL
                     CHECK (RISK_TYPE IN ('WATER','SOIL','DISEASE','MARKET','WEATHER')),
    RISK_SCORE    NUMBER(5,2) NOT NULL CHECK (RISK_SCORE BETWEEN 0 AND 100),
    NOTES         VARCHAR2(300),
    CONSTRAINT PK_CROP_RISK PRIMARY KEY (CROP_RISK_ID),
    CONSTRAINT FK_CRISK_CROP FOREIGN KEY (CROP_ID) REFERENCES CROP (CROP_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_CROP_RISK_TYPE UNIQUE (CROP_ID, RISK_TYPE)
);

-- ---------------------------------------------------------------------
-- 12. CROP_HISTORY — a farmer's actual planting record on a farm.
--     Feeds crop-rotation scoring and the profit/ROI analytics.
-- ---------------------------------------------------------------------
CREATE TABLE CROP_HISTORY (
    HISTORY_ID      NUMBER(10) NOT NULL,
    FARM_ID         NUMBER(10) NOT NULL,
    CROP_ID         NUMBER(10) NOT NULL,
    SEASON_ID       NUMBER(6)  NOT NULL,
    PLANTING_DATE   DATE       NOT NULL,
    HARVEST_DATE    DATE,
    YIELD_QTL       NUMBER(10,2) CHECK (YIELD_QTL >= 0),
    TOTAL_COST      NUMBER(12,2) CHECK (TOTAL_COST >= 0),
    REVENUE         NUMBER(12,2) CHECK (REVENUE >= 0),
    PROFIT          NUMBER(12,2),
    NOTES           VARCHAR2(500),
    CREATED_AT      TIMESTAMP  DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_CROP_HISTORY PRIMARY KEY (HISTORY_ID),
    CONSTRAINT FK_CH_FARM   FOREIGN KEY (FARM_ID)   REFERENCES FARM (FARM_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CH_CROP   FOREIGN KEY (CROP_ID)   REFERENCES CROP (CROP_ID),
    CONSTRAINT FK_CH_SEASON FOREIGN KEY (SEASON_ID) REFERENCES SEASON (SEASON_ID),
    CONSTRAINT CK_CH_DATES  CHECK (HARVEST_DATE IS NULL OR HARVEST_DATE >= PLANTING_DATE)
);
CREATE INDEX IDX_CH_FARM ON CROP_HISTORY (FARM_ID);
CREATE INDEX IDX_CH_CROP ON CROP_HISTORY (CROP_ID);

-- ---------------------------------------------------------------------
-- 13. RECOMMENDATION — a saved snapshot of an engine run, so farmers
--     can revisit past recommendations and admin can see engine usage
-- ---------------------------------------------------------------------
CREATE TABLE RECOMMENDATION (
    RECOMMENDATION_ID NUMBER(10) NOT NULL,
    FARM_ID           NUMBER(10) NOT NULL,
    CROP_ID           NUMBER(10) NOT NULL,
    SUITABILITY_SCORE NUMBER(5,2) NOT NULL CHECK (SUITABILITY_SCORE BETWEEN 0 AND 100),
    RISK_LABEL        VARCHAR2(20) NOT NULL,
    EXPLANATION       VARCHAR2(1000),
    SCENARIO_TAG      VARCHAR2(30) DEFAULT 'CURRENT' NOT NULL,
    CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_RECOMMENDATION PRIMARY KEY (RECOMMENDATION_ID),
    CONSTRAINT FK_REC_FARM FOREIGN KEY (FARM_ID) REFERENCES FARM (FARM_ID) ON DELETE CASCADE,
    CONSTRAINT FK_REC_CROP FOREIGN KEY (CROP_ID) REFERENCES CROP (CROP_ID)
);
CREATE INDEX IDX_REC_FARM ON RECOMMENDATION (FARM_ID);
CREATE INDEX IDX_REC_CROP ON RECOMMENDATION (CROP_ID);

COMMIT;
