-- =====================================================================
-- KRISHIMITRA — SAMPLE / MASTER DATA
-- Run after schema.sql
-- =====================================================================

-- ---------------------------------------------------------------------
-- SOIL
-- ---------------------------------------------------------------------
INSERT INTO SOIL (SOIL_ID, SOIL_NAME, DESCRIPTION) VALUES (SEQ_SOIL_ID.NEXTVAL, 'ALLUVIAL', 'Fertile river-deposited soil, rich in potash, good water retention.');
INSERT INTO SOIL (SOIL_ID, SOIL_NAME, DESCRIPTION) VALUES (SEQ_SOIL_ID.NEXTVAL, 'BLACK', 'Regur soil, high clay content, retains moisture well, ideal for cotton.');
INSERT INTO SOIL (SOIL_ID, SOIL_NAME, DESCRIPTION) VALUES (SEQ_SOIL_ID.NEXTVAL, 'RED', 'Iron-rich soil, well drained, moderate fertility.');
INSERT INTO SOIL (SOIL_ID, SOIL_NAME, DESCRIPTION) VALUES (SEQ_SOIL_ID.NEXTVAL, 'LATERITE', 'Leached, acidic soil found in high rainfall regions.');
INSERT INTO SOIL (SOIL_ID, SOIL_NAME, DESCRIPTION) VALUES (SEQ_SOIL_ID.NEXTVAL, 'SANDY', 'Coarse, low water retention, drains quickly.');
INSERT INTO SOIL (SOIL_ID, SOIL_NAME, DESCRIPTION) VALUES (SEQ_SOIL_ID.NEXTVAL, 'LOAMY', 'Balanced mix of sand, silt and clay; highly fertile and versatile.');
INSERT INTO SOIL (SOIL_ID, SOIL_NAME, DESCRIPTION) VALUES (SEQ_SOIL_ID.NEXTVAL, 'CLAY', 'Fine particles, high water retention, poor drainage.');

-- ---------------------------------------------------------------------
-- SEASON
-- ---------------------------------------------------------------------
INSERT INTO SEASON (SEASON_ID, SEASON_NAME, DESCRIPTION, START_MONTH, END_MONTH) VALUES (SEQ_SEASON_ID.NEXTVAL, 'KHARIF', 'Monsoon crop season', 6, 10);
INSERT INTO SEASON (SEASON_ID, SEASON_NAME, DESCRIPTION, START_MONTH, END_MONTH) VALUES (SEQ_SEASON_ID.NEXTVAL, 'RABI', 'Winter crop season', 11, 3);
INSERT INTO SEASON (SEASON_ID, SEASON_NAME, DESCRIPTION, START_MONTH, END_MONTH) VALUES (SEQ_SEASON_ID.NEXTVAL, 'ZAID', 'Short summer season between Rabi and Kharif', 3, 6);
INSERT INTO SEASON (SEASON_ID, SEASON_NAME, DESCRIPTION, START_MONTH, END_MONTH) VALUES (SEQ_SEASON_ID.NEXTVAL, 'YEAR_ROUND', 'Grown throughout the year given adequate resources', 1, 12);

-- ---------------------------------------------------------------------
-- RESOURCE_ITEM
-- ---------------------------------------------------------------------
INSERT INTO RESOURCE_ITEM (RESOURCE_ID, RESOURCE_NAME, RESOURCE_TYPE, UNIT, AVG_UNIT_COST) VALUES (SEQ_RESOURCE_ID.NEXTVAL, 'Certified Seed', 'SEED', 'kg', 45);
INSERT INTO RESOURCE_ITEM (RESOURCE_ID, RESOURCE_NAME, RESOURCE_TYPE, UNIT, AVG_UNIT_COST) VALUES (SEQ_RESOURCE_ID.NEXTVAL, 'Urea', 'FERTILIZER', 'kg', 6.5);
INSERT INTO RESOURCE_ITEM (RESOURCE_ID, RESOURCE_NAME, RESOURCE_TYPE, UNIT, AVG_UNIT_COST) VALUES (SEQ_RESOURCE_ID.NEXTVAL, 'DAP', 'FERTILIZER', 'kg', 27);
INSERT INTO RESOURCE_ITEM (RESOURCE_ID, RESOURCE_NAME, RESOURCE_TYPE, UNIT, AVG_UNIT_COST) VALUES (SEQ_RESOURCE_ID.NEXTVAL, 'Farmyard Manure', 'FERTILIZER', 'ton', 1200);
INSERT INTO RESOURCE_ITEM (RESOURCE_ID, RESOURCE_NAME, RESOURCE_TYPE, UNIT, AVG_UNIT_COST) VALUES (SEQ_RESOURCE_ID.NEXTVAL, 'Pesticide Spray', 'PESTICIDE', 'litre', 650);
INSERT INTO RESOURCE_ITEM (RESOURCE_ID, RESOURCE_NAME, RESOURCE_TYPE, UNIT, AVG_UNIT_COST) VALUES (SEQ_RESOURCE_ID.NEXTVAL, 'Tractor Hours', 'EQUIPMENT', 'hour', 700);
INSERT INTO RESOURCE_ITEM (RESOURCE_ID, RESOURCE_NAME, RESOURCE_TYPE, UNIT, AVG_UNIT_COST) VALUES (SEQ_RESOURCE_ID.NEXTVAL, 'Farm Labour', 'LABOUR', 'day', 400);
INSERT INTO RESOURCE_ITEM (RESOURCE_ID, RESOURCE_NAME, RESOURCE_TYPE, UNIT, AVG_UNIT_COST) VALUES (SEQ_RESOURCE_ID.NEXTVAL, 'Drip Irrigation Kit', 'EQUIPMENT', 'acre', 35000);

-- ---------------------------------------------------------------------
-- CROP (10 crops, realistic Indian data, deliberately varied)
-- ---------------------------------------------------------------------
INSERT INTO CROP (CROP_ID, CROP_NAME, DESCRIPTION, WATER_REQUIREMENT, GROWTH_DURATION_DAYS, EXPECTED_YIELD_QTL_PER_ACRE, AVG_SELLING_PRICE_PER_QTL, BASE_RISK_LEVEL)
VALUES (SEQ_CROP_ID.NEXTVAL, 'Rice', 'Staple cereal crop grown widely in flooded paddies across India.', 'HIGH', 120, 22, 2100, 'MEDIUM');
INSERT INTO CROP (CROP_ID, CROP_NAME, DESCRIPTION, WATER_REQUIREMENT, GROWTH_DURATION_DAYS, EXPECTED_YIELD_QTL_PER_ACRE, AVG_SELLING_PRICE_PER_QTL, BASE_RISK_LEVEL)
VALUES (SEQ_CROP_ID.NEXTVAL, 'Maize', 'Versatile cereal used for food, feed and industrial starch.', 'MODERATE', 100, 25, 1900, 'LOW');
INSERT INTO CROP (CROP_ID, CROP_NAME, DESCRIPTION, WATER_REQUIREMENT, GROWTH_DURATION_DAYS, EXPECTED_YIELD_QTL_PER_ACRE, AVG_SELLING_PRICE_PER_QTL, BASE_RISK_LEVEL)
VALUES (SEQ_CROP_ID.NEXTVAL, 'Groundnut', 'Oilseed legume that also fixes nitrogen and improves soil health.', 'LOW', 110, 12, 5800, 'LOW');
INSERT INTO CROP (CROP_ID, CROP_NAME, DESCRIPTION, WATER_REQUIREMENT, GROWTH_DURATION_DAYS, EXPECTED_YIELD_QTL_PER_ACRE, AVG_SELLING_PRICE_PER_QTL, BASE_RISK_LEVEL)
VALUES (SEQ_CROP_ID.NEXTVAL, 'Cotton', 'Long-duration cash crop, sensitive to bollworm and market price swings.', 'MODERATE', 180, 8, 7200, 'HIGH');
INSERT INTO CROP (CROP_ID, CROP_NAME, DESCRIPTION, WATER_REQUIREMENT, GROWTH_DURATION_DAYS, EXPECTED_YIELD_QTL_PER_ACRE, AVG_SELLING_PRICE_PER_QTL, BASE_RISK_LEVEL)
VALUES (SEQ_CROP_ID.NEXTVAL, 'Ragi', 'Hardy millet, drought tolerant, thrives on marginal land.', 'LOW', 105, 10, 3400, 'LOW');
INSERT INTO CROP (CROP_ID, CROP_NAME, DESCRIPTION, WATER_REQUIREMENT, GROWTH_DURATION_DAYS, EXPECTED_YIELD_QTL_PER_ACRE, AVG_SELLING_PRICE_PER_QTL, BASE_RISK_LEVEL)
VALUES (SEQ_CROP_ID.NEXTVAL, 'Wheat', 'Winter cereal, requires cool growing weather and moderate irrigation.', 'MODERATE', 130, 20, 2300, 'MEDIUM');
INSERT INTO CROP (CROP_ID, CROP_NAME, DESCRIPTION, WATER_REQUIREMENT, GROWTH_DURATION_DAYS, EXPECTED_YIELD_QTL_PER_ACRE, AVG_SELLING_PRICE_PER_QTL, BASE_RISK_LEVEL)
VALUES (SEQ_CROP_ID.NEXTVAL, 'Sugarcane', 'Long-duration, water-intensive cash crop with stable mill demand.', 'HIGH', 330, 350, 320, 'MEDIUM');
INSERT INTO CROP (CROP_ID, CROP_NAME, DESCRIPTION, WATER_REQUIREMENT, GROWTH_DURATION_DAYS, EXPECTED_YIELD_QTL_PER_ACRE, AVG_SELLING_PRICE_PER_QTL, BASE_RISK_LEVEL)
VALUES (SEQ_CROP_ID.NEXTVAL, 'Tomato', 'High-value vegetable with short duration but volatile market prices.', 'MODERATE', 90, 90, 1200, 'HIGH');
INSERT INTO CROP (CROP_ID, CROP_NAME, DESCRIPTION, WATER_REQUIREMENT, GROWTH_DURATION_DAYS, EXPECTED_YIELD_QTL_PER_ACRE, AVG_SELLING_PRICE_PER_QTL, BASE_RISK_LEVEL)
VALUES (SEQ_CROP_ID.NEXTVAL, 'Onion', 'Widely cultivated bulb vegetable, price-sensitive, storable.', 'MODERATE', 120, 80, 1500, 'MEDIUM');
INSERT INTO CROP (CROP_ID, CROP_NAME, DESCRIPTION, WATER_REQUIREMENT, GROWTH_DURATION_DAYS, EXPECTED_YIELD_QTL_PER_ACRE, AVG_SELLING_PRICE_PER_QTL, BASE_RISK_LEVEL)
VALUES (SEQ_CROP_ID.NEXTVAL, 'Pearl Millet (Bajra)', 'Extremely drought-hardy millet suited to arid, sandy tracts.', 'LOW', 85, 9, 2500, 'LOW');

-- ---------------------------------------------------------------------
-- Helper: resolve IDs via subqueries so the script does not depend on
-- guessing sequence values (works regardless of insert order above).
-- ---------------------------------------------------------------------

-- CROP_SOIL (suitability)
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'EXCELLENT' FROM CROP c, SOIL s WHERE c.CROP_NAME='Rice' AND s.SOIL_NAME='ALLUVIAL';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'GOOD' FROM CROP c, SOIL s WHERE c.CROP_NAME='Rice' AND s.SOIL_NAME='CLAY';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'EXCELLENT' FROM CROP c, SOIL s WHERE c.CROP_NAME='Maize' AND s.SOIL_NAME='LOAMY';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'GOOD' FROM CROP c, SOIL s WHERE c.CROP_NAME='Maize' AND s.SOIL_NAME='ALLUVIAL';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'EXCELLENT' FROM CROP c, SOIL s WHERE c.CROP_NAME='Groundnut' AND s.SOIL_NAME='RED';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'GOOD' FROM CROP c, SOIL s WHERE c.CROP_NAME='Groundnut' AND s.SOIL_NAME='SANDY';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'EXCELLENT' FROM CROP c, SOIL s WHERE c.CROP_NAME='Cotton' AND s.SOIL_NAME='BLACK';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'FAIR' FROM CROP c, SOIL s WHERE c.CROP_NAME='Cotton' AND s.SOIL_NAME='ALLUVIAL';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'EXCELLENT' FROM CROP c, SOIL s WHERE c.CROP_NAME='Ragi' AND s.SOIL_NAME='RED';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'GOOD' FROM CROP c, SOIL s WHERE c.CROP_NAME='Ragi' AND s.SOIL_NAME='LATERITE';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'EXCELLENT' FROM CROP c, SOIL s WHERE c.CROP_NAME='Wheat' AND s.SOIL_NAME='ALLUVIAL';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'GOOD' FROM CROP c, SOIL s WHERE c.CROP_NAME='Wheat' AND s.SOIL_NAME='LOAMY';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'EXCELLENT' FROM CROP c, SOIL s WHERE c.CROP_NAME='Sugarcane' AND s.SOIL_NAME='ALLUVIAL';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'GOOD' FROM CROP c, SOIL s WHERE c.CROP_NAME='Sugarcane' AND s.SOIL_NAME='BLACK';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'EXCELLENT' FROM CROP c, SOIL s WHERE c.CROP_NAME='Tomato' AND s.SOIL_NAME='LOAMY';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'GOOD' FROM CROP c, SOIL s WHERE c.CROP_NAME='Tomato' AND s.SOIL_NAME='RED';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'EXCELLENT' FROM CROP c, SOIL s WHERE c.CROP_NAME='Onion' AND s.SOIL_NAME='LOAMY';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'GOOD' FROM CROP c, SOIL s WHERE c.CROP_NAME='Onion' AND s.SOIL_NAME='BLACK';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'EXCELLENT' FROM CROP c, SOIL s WHERE c.CROP_NAME='Pearl Millet (Bajra)' AND s.SOIL_NAME='SANDY';
INSERT INTO CROP_SOIL SELECT c.CROP_ID, s.SOIL_ID, 'GOOD' FROM CROP c, SOIL s WHERE c.CROP_NAME='Pearl Millet (Bajra)' AND s.SOIL_NAME='RED';

-- CROP_SEASON
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Rice' AND s.SEASON_NAME='KHARIF';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Maize' AND s.SEASON_NAME='KHARIF';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Maize' AND s.SEASON_NAME='RABI';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Groundnut' AND s.SEASON_NAME='KHARIF';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Groundnut' AND s.SEASON_NAME='ZAID';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Cotton' AND s.SEASON_NAME='KHARIF';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Ragi' AND s.SEASON_NAME='KHARIF';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Wheat' AND s.SEASON_NAME='RABI';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Sugarcane' AND s.SEASON_NAME='YEAR_ROUND';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Tomato' AND s.SEASON_NAME='RABI';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Tomato' AND s.SEASON_NAME='ZAID';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Onion' AND s.SEASON_NAME='RABI';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Pearl Millet (Bajra)' AND s.SEASON_NAME='KHARIF';
INSERT INTO CROP_SEASON SELECT c.CROP_ID, s.SEASON_ID FROM CROP c, SEASON s WHERE c.CROP_NAME='Pearl Millet (Bajra)' AND s.SEASON_NAME='ZAID';

-- CROP_COST (per acre, INR)
INSERT INTO CROP_COST (CROP_COST_ID, CROP_ID, SEED_COST, FERTILIZER_COST, LABOUR_COST, IRRIGATION_COST, OTHER_COST)
  SELECT SEQ_CROP_COST_ID.NEXTVAL, CROP_ID, 3200, 6500, 9000, 7000, 1800 FROM CROP WHERE CROP_NAME='Rice';
INSERT INTO CROP_COST (CROP_COST_ID, CROP_ID, SEED_COST, FERTILIZER_COST, LABOUR_COST, IRRIGATION_COST, OTHER_COST)
  SELECT SEQ_CROP_COST_ID.NEXTVAL, CROP_ID, 2400, 5200, 6000, 3500, 1200 FROM CROP WHERE CROP_NAME='Maize';
INSERT INTO CROP_COST (CROP_COST_ID, CROP_ID, SEED_COST, FERTILIZER_COST, LABOUR_COST, IRRIGATION_COST, OTHER_COST)
  SELECT SEQ_CROP_COST_ID.NEXTVAL, CROP_ID, 4500, 3800, 5500, 2000, 1500 FROM CROP WHERE CROP_NAME='Groundnut';
INSERT INTO CROP_COST (CROP_COST_ID, CROP_ID, SEED_COST, FERTILIZER_COST, LABOUR_COST, IRRIGATION_COST, OTHER_COST)
  SELECT SEQ_CROP_COST_ID.NEXTVAL, CROP_ID, 3600, 7200, 14000, 6000, 3200 FROM CROP WHERE CROP_NAME='Cotton';
INSERT INTO CROP_COST (CROP_COST_ID, CROP_ID, SEED_COST, FERTILIZER_COST, LABOUR_COST, IRRIGATION_COST, OTHER_COST)
  SELECT SEQ_CROP_COST_ID.NEXTVAL, CROP_ID, 1200, 2600, 4200, 1000, 900 FROM CROP WHERE CROP_NAME='Ragi';
INSERT INTO CROP_COST (CROP_COST_ID, CROP_ID, SEED_COST, FERTILIZER_COST, LABOUR_COST, IRRIGATION_COST, OTHER_COST)
  SELECT SEQ_CROP_COST_ID.NEXTVAL, CROP_ID, 2800, 6000, 6500, 4200, 1400 FROM CROP WHERE CROP_NAME='Wheat';
INSERT INTO CROP_COST (CROP_COST_ID, CROP_ID, SEED_COST, FERTILIZER_COST, LABOUR_COST, IRRIGATION_COST, OTHER_COST)
  SELECT SEQ_CROP_COST_ID.NEXTVAL, CROP_ID, 9000, 15000, 32000, 22000, 6000 FROM CROP WHERE CROP_NAME='Sugarcane';
INSERT INTO CROP_COST (CROP_COST_ID, CROP_ID, SEED_COST, FERTILIZER_COST, LABOUR_COST, IRRIGATION_COST, OTHER_COST)
  SELECT SEQ_CROP_COST_ID.NEXTVAL, CROP_ID, 5500, 8000, 18000, 8000, 4500 FROM CROP WHERE CROP_NAME='Tomato';
INSERT INTO CROP_COST (CROP_COST_ID, CROP_ID, SEED_COST, FERTILIZER_COST, LABOUR_COST, IRRIGATION_COST, OTHER_COST)
  SELECT SEQ_CROP_COST_ID.NEXTVAL, CROP_ID, 4800, 7200, 15000, 6500, 3000 FROM CROP WHERE CROP_NAME='Onion';
INSERT INTO CROP_COST (CROP_COST_ID, CROP_ID, SEED_COST, FERTILIZER_COST, LABOUR_COST, IRRIGATION_COST, OTHER_COST)
  SELECT SEQ_CROP_COST_ID.NEXTVAL, CROP_ID, 900, 2200, 3800, 800, 700 FROM CROP WHERE CROP_NAME='Pearl Millet (Bajra)';

-- CROP_RESOURCE
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 25 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Rice' AND r.RESOURCE_NAME='Certified Seed';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 60 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Rice' AND r.RESOURCE_NAME='Urea';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 8 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Maize' AND r.RESOURCE_NAME='Certified Seed';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 45 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Maize' AND r.RESOURCE_NAME='Urea';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 40 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Groundnut' AND r.RESOURCE_NAME='Certified Seed';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 20 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Groundnut' AND r.RESOURCE_NAME='DAP';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 5 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Cotton' AND r.RESOURCE_NAME='Certified Seed';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 3 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Cotton' AND r.RESOURCE_NAME='Pesticide Spray';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 6 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Ragi' AND r.RESOURCE_NAME='Certified Seed';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 40 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Wheat' AND r.RESOURCE_NAME='Certified Seed';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 50 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Wheat' AND r.RESOURCE_NAME='DAP';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 1 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Sugarcane' AND r.RESOURCE_NAME='Drip Irrigation Kit';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 2 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Tomato' AND r.RESOURCE_NAME='Pesticide Spray';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 30 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Onion' AND r.RESOURCE_NAME='DAP';
INSERT INTO CROP_RESOURCE SELECT c.CROP_ID, r.RESOURCE_ID, 4 FROM CROP c, RESOURCE_ITEM r WHERE c.CROP_NAME='Pearl Millet (Bajra)' AND r.RESOURCE_NAME='Certified Seed';

-- CROP_RISK (WATER, SOIL, DISEASE, MARKET, WEATHER — sums vary intentionally)
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WATER', 65, 'Needs standing water; vulnerable to drought years' FROM CROP WHERE CROP_NAME='Rice';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'SOIL', 20, 'Tolerant of a range of soils if water is available' FROM CROP WHERE CROP_NAME='Rice';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'DISEASE', 35, 'Blast and bacterial blight in humid conditions' FROM CROP WHERE CROP_NAME='Rice';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'MARKET', 25, 'MSP-backed, relatively stable procurement' FROM CROP WHERE CROP_NAME='Rice';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WEATHER', 40, 'Sensitive to erratic monsoon timing' FROM CROP WHERE CROP_NAME='Rice';

INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WATER', 35, 'Moderate irrigation need' FROM CROP WHERE CROP_NAME='Maize';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'SOIL', 15, 'Adapts well to loamy and alluvial soils' FROM CROP WHERE CROP_NAME='Maize';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'DISEASE', 25, 'Fall armyworm risk in some regions' FROM CROP WHERE CROP_NAME='Maize';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'MARKET', 30, 'Demand from feed and starch industry is steady' FROM CROP WHERE CROP_NAME='Maize';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WEATHER', 30, 'Reasonably weather tolerant' FROM CROP WHERE CROP_NAME='Maize';

INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WATER', 20, 'Drought tolerant oilseed' FROM CROP WHERE CROP_NAME='Groundnut';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'SOIL', 15, 'Prefers well-drained sandy/red soils' FROM CROP WHERE CROP_NAME='Groundnut';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'DISEASE', 30, 'Leaf spot and rust in wet spells' FROM CROP WHERE CROP_NAME='Groundnut';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'MARKET', 35, 'Price depends on edible-oil import policy' FROM CROP WHERE CROP_NAME='Groundnut';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WEATHER', 25, 'Fairly weather resilient once established' FROM CROP WHERE CROP_NAME='Groundnut';

INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WATER', 45, 'Needs consistent moisture during boll formation' FROM CROP WHERE CROP_NAME='Cotton';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'SOIL', 20, 'Thrives on black cotton soil' FROM CROP WHERE CROP_NAME='Cotton';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'DISEASE', 60, 'Bollworm and whitefly are persistent threats' FROM CROP WHERE CROP_NAME='Cotton';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'MARKET', 55, 'International cotton prices are volatile' FROM CROP WHERE CROP_NAME='Cotton';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WEATHER', 45, 'Long duration exposes it to more weather events' FROM CROP WHERE CROP_NAME='Cotton';

INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WATER', 10, 'One of the most drought-hardy cereals' FROM CROP WHERE CROP_NAME='Ragi';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'SOIL', 15, 'Grows on marginal, low-fertility land' FROM CROP WHERE CROP_NAME='Ragi';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'DISEASE', 20, 'Generally low pest pressure' FROM CROP WHERE CROP_NAME='Ragi';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'MARKET', 30, 'Niche but growing millet market' FROM CROP WHERE CROP_NAME='Ragi';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WEATHER', 15, 'Very weather resilient' FROM CROP WHERE CROP_NAME='Ragi';

INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WATER', 40, 'Needs timely irrigation at key growth stages' FROM CROP WHERE CROP_NAME='Wheat';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'SOIL', 15, 'Well suited to alluvial plains' FROM CROP WHERE CROP_NAME='Wheat';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'DISEASE', 30, 'Rust risk in humid winters' FROM CROP WHERE CROP_NAME='Wheat';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'MARKET', 20, 'MSP-backed procurement' FROM CROP WHERE CROP_NAME='Wheat';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WEATHER', 30, 'Unseasonal rain near harvest can hurt quality' FROM CROP WHERE CROP_NAME='Wheat';

INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WATER', 70, 'Very high, continuous water demand' FROM CROP WHERE CROP_NAME='Sugarcane';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'SOIL', 20, 'Prefers deep, fertile alluvial soil' FROM CROP WHERE CROP_NAME='Sugarcane';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'DISEASE', 35, 'Red rot in waterlogged fields' FROM CROP WHERE CROP_NAME='Sugarcane';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'MARKET', 30, 'Mill-linked pricing, generally stable' FROM CROP WHERE CROP_NAME='Sugarcane';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WEATHER', 25, 'Long duration but fairly weather tolerant' FROM CROP WHERE CROP_NAME='Sugarcane';

INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WATER', 40, 'Needs even moisture, sensitive to both excess and deficit' FROM CROP WHERE CROP_NAME='Tomato';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'SOIL', 20, 'Prefers well-drained loamy soil' FROM CROP WHERE CROP_NAME='Tomato';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'DISEASE', 55, 'Blight and fruit borer are common' FROM CROP WHERE CROP_NAME='Tomato';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'MARKET', 70, 'Highly volatile mandi prices' FROM CROP WHERE CROP_NAME='Tomato';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WEATHER', 40, 'Sensitive to heat spells and heavy rain' FROM CROP WHERE CROP_NAME='Tomato';

INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WATER', 35, 'Moderate, even irrigation needed at bulbing' FROM CROP WHERE CROP_NAME='Onion';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'SOIL', 20, 'Prefers loamy, well-drained soil' FROM CROP WHERE CROP_NAME='Onion';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'DISEASE', 35, 'Purple blotch in humid weather' FROM CROP WHERE CROP_NAME='Onion';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'MARKET', 65, 'Notoriously volatile market prices' FROM CROP WHERE CROP_NAME='Onion';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WEATHER', 30, 'Untimely rain can damage bulbs at harvest' FROM CROP WHERE CROP_NAME='Onion';

INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WATER', 10, 'Exceptionally drought tolerant' FROM CROP WHERE CROP_NAME='Pearl Millet (Bajra)';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'SOIL', 10, 'Thrives in sandy, arid soils' FROM CROP WHERE CROP_NAME='Pearl Millet (Bajra)';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'DISEASE', 20, 'Low pest and disease pressure' FROM CROP WHERE CROP_NAME='Pearl Millet (Bajra)';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'MARKET', 30, 'Growing demand under millet promotion schemes' FROM CROP WHERE CROP_NAME='Pearl Millet (Bajra)';
INSERT INTO CROP_RISK SELECT SEQ_CROP_RISK_ID.NEXTVAL, CROP_ID, 'WEATHER', 15, 'Very weather resilient' FROM CROP WHERE CROP_NAME='Pearl Millet (Bajra)';

-- ---------------------------------------------------------------------
-- ADMIN_USER (dev default — password 'Admin@123', bcrypt hash generated
-- by the Flask app's own hashing utility; see README for how to reset)
-- ---------------------------------------------------------------------
INSERT INTO ADMIN_USER (ADMIN_ID, FULL_NAME, EMAIL, PASSWORD_HASH)
VALUES (SEQ_ADMIN_ID.NEXTVAL, 'KrishiMitra Admin', 'admin@krishimitra.in',
        '$2b$12$nggXbnRBCJUI8N6fwQc/5uZ5euJiX6.5JSpIVpzS83RwoDxXMJxUa');

-- ---------------------------------------------------------------------
-- Demo FARMER (password 'Farmer@123')
-- ---------------------------------------------------------------------
INSERT INTO FARMER (FARMER_ID, FULL_NAME, EMAIL, PHONE, PASSWORD_HASH, STATE, DISTRICT)
VALUES (SEQ_FARMER_ID.NEXTVAL, 'Ramesh Kumar', 'ramesh.kumar@example.com', '9876543210',
        '$2b$12$YRfaTXw6Xmv7fUfVjrzWZ.oHfPhJbHporz4Y4JPM1WEPZXtw.9fmi',
        'Karnataka', 'Mandya');

INSERT INTO FARM (FARM_ID, FARMER_ID, FARM_NAME, LOCATION, LAND_AREA_ACRES, SOIL_ID, IRRIGATION_TYPE, WATER_AVAILABILITY, CURRENT_SEASON_ID, NOTES)
SELECT SEQ_FARM_ID.NEXTVAL, f.FARMER_ID, 'Ramesh Home Farm', 'Mandya, Karnataka', 3.5, s.SOIL_ID, 'BOREWELL', 'MODERATE', se.SEASON_ID, 'Near the Cauvery canal command area.'
FROM FARMER f, SOIL s, SEASON se
WHERE f.EMAIL='ramesh.kumar@example.com' AND s.SOIL_NAME='RED' AND se.SEASON_NAME='KHARIF';

INSERT INTO CROP_HISTORY (HISTORY_ID, FARM_ID, CROP_ID, SEASON_ID, PLANTING_DATE, HARVEST_DATE, YIELD_QTL, TOTAL_COST, REVENUE, PROFIT, NOTES)
SELECT SEQ_CROP_HISTORY_ID.NEXTVAL, fm.FARM_ID, c.CROP_ID, se.SEASON_ID,
       DATE '2025-06-15', DATE '2025-10-05', 38, 32000, 79800, 47800, 'Good rainfall year.'
FROM FARM fm, CROP c, SEASON se
WHERE fm.FARM_NAME='Ramesh Home Farm' AND c.CROP_NAME='Groundnut' AND se.SEASON_NAME='KHARIF';

COMMIT;
